apiVersion: apps/v1
kind: Deployment
metadata:
  name: away-from-keyboard
spec:
  replicas: 1
  selector:
    matchLabels:
      name: away-from-keyboard
  template:
    metadata:
      labels:
        name: away-from-keyboard
    spec:
      containers:
      - name: away-from-keyboard-api
        imagePullPolicy: Never
        image: slack-afk:latest
        tty: true
        args: ["unicorn", "-c", "config/unicorn.rb", "-p", "8080"]
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 65534
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          httpGet:
            path: /
            port: 8080
        env:
          - name: TZ
            value: Asia/Tokyo
          - name: LANG
            value: C.UTF-8
          - name: APP_ENV
            value: "production"
          - name: SLACK_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: away-from-keyboard-secret
                key: slack-api-token
          - name: SLACK_SIGNING_SECRET
            valueFrom:
              secretKeyRef:
                name: away-from-keyboard-secret
                key: slack-signing-secret
      - name: away-from-keyboard-bot
        args: ["ruby", "bot.rb"]
        image: slack-afk:latest
        imagePullPolicy: Never
        tty: true
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 65534 # nobody
          runAsNonRoot: true
        readinessProbe:
          tcpSocket:
            port: 1234
          initialDelaySeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 1234
          initialDelaySeconds: 3
          periodSeconds: 10
        env:
          - name: TZ
            value: Asia/Tokyo
          - name: LANG
            value: C.UTF-8
          - name: APP_ENV
            value: "production"
          - name: SLACK_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: away-from-keyboard-secret
                key: slack-api-token
          - name: SLACK_SIGNING_SECRET
            valueFrom:
              secretKeyRef:
                name: away-from-keyboard-secret
                key: slack-signing-secret
      - name: redis
        image: redis
        tty: true
        ports:
        - containerPort: 6379
